on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm install
    - name: Run tests (Linux)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Run tests (Non-Linux)
      run: npm test
      if: runner.os != 'Linux'
    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results-${{ runner.os }}
        path: ./out/test/**/*
        if-no-files-found: ignore